monocleaner-download quiet mode
Closes #3

diff --git a/scripts/monocleaner-download b/scripts/monocleaner-download
--- a/scripts/monocleaner-download
+++ b/scripts/monocleaner-download
@@ -3,31 +3,42 @@
 usage() {
     echo "Script to download Bicleaner language packs."
     echo
-    echo "Usage: `basename $0` <lang> <download_path>"
-    echo "      <lang>         Language code."
-    echo "      <download_path> Path where downloaded language pack should be placed."
+    echo "Usage: `basename $0` <lang> [download_path]"
+    echo "      -q              Quiet mode."
+    echo "      -h              Show this help message."
+    echo "      <lang>          Language code."
+    echo "      [download_path] Path where downloaded language pack should be placed."
+    echo "                      Default: current path."
 }
 
 invalid_url(){
     wget -S --spider -o - $1 | grep -q '404 Not Found'
 }
 
-if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];
+WGETQUIET=""
+TAROPS="xvf"
+while getopts "qh" options
+do
+    case "${options}" in
+        q) WGETQUIET="-q"
+            TAROPS="xf";;
+        h) usage
+            exit 0;;
+        \?) usage 1>&2
+            exit 1;;
+    esac
+done
+
+URL="https://github.com/bitextor/monocleaner-data/releases/latest/download"
+L1=${@:$OPTIND:1}
+DOWNLOAD_PATH=${@:$OPTIND+1:1}
+if [ -z $L1 ];
 then
-    usage 2>&1
-    exit 0
-elif [[ $# -lt 2 ]];
-then
-    echo "Wrong number of arguments: $@" 2>&1
+    echo "Error language is mandatory: $@" 2>&1
     usage 2>&1
     exit 1
 fi
-
-URL="https://github.com/bitextor/monocleaner-data/releases/latest/download"
-L1=$1
-if [ "$2" != "" ]; then
-    DOWNLOAD_PATH=$2
-else
+if [ "$DOWNLOAD_PATH" == "" ]; then
     DOWNLOAD_PATH="."
 fi
 
@@ -35,9 +46,11 @@ if invalid_url $URL/$L1.tgz
 then
     >&2 echo $L1 language pack does not exist
 else
-    wget -P $DOWNLOAD_PATH $URL/$L1.tgz
-    tar xvf $DOWNLOAD_PATH/$L1.tgz -C $DOWNLOAD_PATH
+    wget $WGETQUIET -P $DOWNLOAD_PATH $URL/$L1.tgz
+    tar $TAROPS $DOWNLOAD_PATH/$L1.tgz -C $DOWNLOAD_PATH
     rm $DOWNLOAD_PATH/$L1.tgz
 fi
 
-echo Finished >&2
+if [ -z $WGETQUIET ]; then
+    echo Finished >&2
+fi
